# Generated by Django 3.1.3 on 2020-12-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='familiaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.familia'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='articuloId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.articulo'),
        ),
    ]
