# Generated by Django 3.1.3 on 2020-12-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_auto_20201214_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
